### ISSUE TITLE
Continuous Errors and not actually working

### ISSUE THREAD

**Issue by paulincai** [kenylieou/prerender-request-blacklist#1]
Hi,

I tried to use this plugin with the last version of Prerender (5.5.1) with Redis prerender-redis-cache 0.2.0. When I add this plugin I get the following errors. "engine.montiapm.com" is actually one of the domains I set as blocked. Removing the plugin results in normal work of Prerender with no errors.

```
2019-03-18T12:17:14.430Z - 0 https://engine.montiapm.com/simplentp/sync                                                                                                                                  
2019-03-18T12:17:14.432Z + 1 https://engine.montiapm.com/simplentp/sync                                                                                                                                  
(node:1504) UnhandledPromiseRejectionWarning: Error: Response already processed.                                                                                                                         
    at /home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/chrome.js:96:30                                                                                                   
    at Chrome.handleMessage (/home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/chrome.js:297:13)                                                                           
    at WebSocket.<anonymous> (/home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/chrome.js:274:27)                                                                          
    at WebSocket.emit (events.js:189:13)                                                                                                                                                                 
    at Receiver._receiver.onmessage (/home/prerender/node_modules/prerender/node_modules/ws/lib/WebSocket.js:141:47)                                                                                     
    at Receiver.dataMessage (/home/prerender/node_modules/prerender/node_modules/ws/lib/Receiver.js:389:14)                                                                                              
    at perMessageDeflate.decompress (/home/prerender/node_modules/prerender/node_modules/ws/lib/Receiver.js:349:40)                                                                                      
    at _decompress (/home/prerender/node_modules/prerender/node_modules/ws/lib/PerMessageDeflate.js:306:9)                                                                                               
    at _inflate.flush (/home/prerender/node_modules/prerender/node_modules/ws/lib/PerMessageDeflate.js:386:7)                                                                                            
    at afterWrite (_stream_writable.js:480:3)                                                                                                                                                            
(node:1504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which wa
s not handled with .catch(). (rejection id: 48)                                                                                                                                                          
2019-03-18T12:17:14.464Z - 0 https://engine.montiapm.com/simplentp/sync                                                                                                                                  
2019-03-18T12:17:16.181Z + 1 https://engine.montiapm.com/simplentp/sync                                                                                                                                  
(node:1504) UnhandledPromiseRejectionWarning: Error: Response already processed.                                                                                                                         
    at /home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/chrome.js:96:30                                                                                                   
    at Chrome.handleMessage (/home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/chrome.js:297:13)                                                                           
    at WebSocket.<anonymous> (/home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/chrome.js:274:27)                                                                          
    at WebSocket.emit (events.js:189:13)                                                                                                                                                                 
    at Receiver._receiver.onmessage (/home/prerender/node_modules/prerender/node_modules/ws/lib/WebSocket.js:141:47)                                                                                     
    at Receiver.dataMessage (/home/prerender/node_modules/prerender/node_modules/ws/lib/Receiver.js:389:14)                                                                                              
    at perMessageDeflate.decompress (/home/prerender/node_modules/prerender/node_modules/ws/lib/Receiver.js:349:40)                                                                                      
    at _decompress (/home/prerender/node_modules/prerender/node_modules/ws/lib/PerMessageDeflate.js:306:9)                                                                                               
    at _inflate.flush (/home/prerender/node_modules/prerender/node_modules/ws/lib/PerMessageDeflate.js:386:7)                                                                                            
    at afterWrite (_stream_writable.js:480:3)                                                                                                                                                            
(node:1504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which wa
s not handled with .catch(). (rejection id: 49)                                                                                                                                                          
2019-03-18T12:17:16.243Z - 0 https://engine.montiapm.com/simplentp/sync                                                                                                                                  
2019-03-18T12:17:16.245Z + 1 https://engine.montiapm.com/simplentp/sync                                                                                                                                  
(node:1504) UnhandledPromiseRejectionWarning: Error: Response already processed.                                                                                                                         
    at /home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/chrome.js:96:30                                                                                                   
    at Chrome.handleMessage (/home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/chrome.js:297:13)                                                                           
    at WebSocket.<anonymous> (/home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/chrome.js:274:27)                                                                          
    at WebSocket.emit (events.js:189:13)                                                                                                                                                                 
    at Receiver._receiver.onmessage (/home/prerender/node_modules/prerender/node_modules/ws/lib/WebSocket.js:141:47)                                                                                     
    at Receiver.dataMessage (/home/prerender/node_modules/prerender/node_modules/ws/lib/Receiver.js:389:14)                                                                                              
    at perMessageDeflate.decompress (/home/prerender/node_modules/prerender/node_modules/ws/lib/Receiver.js:349:40)                                                                                      
    at _decompress (/home/prerender/node_modules/prerender/node_modules/ws/lib/PerMessageDeflate.js:306:9)                                                                                               
    at _inflate.flush (/home/prerender/node_modules/prerender/node_modules/ws/lib/PerMessageDeflate.js:386:7)                                                                                            
    at afterWrite (_stream_writable.js:480:3)                                                                                                                                                            
(node:1504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which wa
s not handled with .catch(). (rejection id: 50)                                                                                                                                                          
2019-03-18T12:17:16.270Z - 0 https://engine.montiapm.com/simplentp/sync                                                                                                                                  
2019-03-18T12:17:21.205Z page timed out https://www.activitree.com/education/view/gJoB42igoSaHRy9Pp                                                                                                      
2019-03-18T12:17:21.264Z got 200 in 20202ms for https://www.activitree.com/education/view/gJoB42igoSaHRy9Pp                                                                                              
2019-03-18T12:17:23.091Z page timed out https://www.activitree.com/education/view/gJoB42igoSaHRy9Pp                                                                                                      
2019-03-18T12:17:23.134Z got 200 in 20193ms for https://www.activitree.com/education/view/gJoB42igoSaHRy9Pp                                                                                              
2019-03-18T12:17:25.238Z page timed out https://www.activitree.com/education/view/gJoB42igoSaHRy9Pp                                                                                                      
2019-03-18T12:17:25.271Z Restarting Chrome                                                                                                                                                               
2019-03-18T12:17:25.296Z got 200 in 20227ms for https://www.activitree.com/education/view/gJoB42igoSaHRy9Pp                                                                                              
2019-03-18T12:17:25.303Z Chrome connection closed... restarting Chrome                                                                                                                                   
2019-03-18T12:17:25.304Z Starting Chrome                                                                                                                                                                 
2019-03-18T12:17:25.310Z error closing Chrome tab Error: not opened                                                                                                                                      
    at WebSocket.send (/home/prerender/node_modules/prerender/node_modules/ws/lib/WebSocket.js:359:18)                                                                                                   
    at Chrome.enqueueCommand (/home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/chrome.js:130:16)                                                                          
    at /home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/chrome.js:88:28                                                                                                   
    at new Promise (<anonymous>)                                                                                                                                                                         
    at Chrome.send (/home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/chrome.js:87:16)                                                                                     
    at Object.handler [as disposeBrowserContext] (/home/prerender/node_modules/prerender/node_modules/chrome-remote-interface/lib/api.js:32:23)                                                          
    at tab.browser.Target.closeTarget.then (/home/prerender/node_modules/prerender/lib/browsers/chrome.js:149:30)                                                                                        
    at process._tickCallback (internal/process/next_tick.js:68:7)   

```

**Comment by kenylieou** [comment]
Hi @paulincai Is there any url using montiapm that you can able to share in order to reproduce?

**Comment by paulincai** [comment]
Hi @kenylieou. Very nice of you to get back.  I use a Meteor Web App.  I know what MontiAPM is but I can't say that I know its internals so I cannot present too much background of it. Monti is a monitoring tool for Meteor (traditionally known as Kadira). There is a Monti "client" installed on the Node server which communicates permanently with the MontiAPM server (https://app.montiapm.com/) and transmits analytics like memory and CPU used by the Node server, number of subscriptions to Mongo, time of response to queries etc. If you check the body tag of my SPA at https://www.activitree.com, at the bottom you find the Meteor JS bundle where Monti is showing. Like in the image below.
![Screen Shot 2019-03-19 at 22 32 51](https://user-images.githubusercontent.com/26188915/54632467-9a415200-4a97-11e9-9580-26b63252b25e.png)

**Comment by kenylieou** [comment]
In your logs: 

```
2019-03-18T12:17:14.430Z - 0 https://engine.montiapm.com/simplentp/sync                                                                                                                                  
2019-03-18T12:17:14.432Z + 1 https://engine.montiapm.com/simplentp/sync
```

You are turning `logRequests: true`, do you see something like 
```
- BLOCK https://www.google-analytics.com/analytics.js by rule domain:google-analytics.com
2019-03-20T08:20:24.863Z + 1 https://www.google-analytics.com/analytics.js
2019-03-20T08:20:24.887Z - 0 https://www.google-analytics.com/analytics.js
```
in your console? 

btw, do you enable `ENABLE_SERVICE_WORKER=true` of prerender?

**Comment by paulincai** [comment]
do you enable ENABLE_SERVICE_WORKER=true of prerender?
No.
My Prerender Server JS file:

```
var prerender = require('prerender');                                                                                         
var redis = require('redis')                                                                                                  
                                                                                                                              
const client = redis.createClient()                                                                                           
                                                                                                                              
var server = prerender({                                                                                                      
        logRequests: true                                                                                                     
});                                                                                                                           
                                                                                                                              
// server.use(require('prerender-request-blacklist'));                                                                        
process.env.PAGE_TTL = 3600 * 24 * 7; // change to 0 if you want all time cache                                               
server.use(require('prerender-redis-cache'));                                                                                 
server.use(prerender.sendPrerenderHeader());                                                                                  
server.use(prerender.blockResources());                                                                                       
server.use(prerender.removeScriptTags());                                                                                     
server.use(prerender.httpHeaders());                                                                                          
                                                                                                                              
// server.use(prerender.basicAuth());                                                                                         
                                                                                                                              
server.start(); 
```

A full log when I prerender (Fetch as Google):
```
2019-03-22T18:36:16.275Z getting https://www.activitree.com/education/type=all&curr=Canadian                                                                                               
2019-03-22T18:36:16.380Z + 1 https://www.activitree.com/education/type=all&curr=Canadian                                                                                                   
2019-03-22T18:36:16.507Z - 0 https://www.activitree.com/education/type=all&curr=Canadian                                                                                                   
2019-03-22T18:36:16.527Z + 1 https://www.activitree.com/81c5d84a966fa05d60cc294a8115a98e1910ac90.css?meteor_css_resource=true                                                              
2019-03-22T18:36:16.528Z + 2 https://www.activitree.com/87879f8e69875bd8123eea1099de5a67ff26599c.js?meteor_js_resource=true                                                                
2019-03-22T18:36:16.559Z - 1 https://www.activitree.com/81c5d84a966fa05d60cc294a8115a98e1910ac90.css?meteor_css_resource=true                                                              
2019-03-22T18:36:16.608Z - 0 https://www.activitree.com/87879f8e69875bd8123eea1099de5a67ff26599c.js?meteor_js_resource=true                                                                
2019-03-22T18:36:17.075Z + 1 https://www.activitree.com/sockjs/info?cb=scbb2vcvlr                                                                                                          
2019-03-22T18:36:17.112Z + 2 https://www.activitree.com/__meteor__/dynamic-import/fetch                                                                                                    
2019-03-22T18:36:17.119Z - 1 https://www.activitree.com/sockjs/info?cb=scbb2vcvlr                                                                                                          
2019-03-22T18:36:17.170Z - 0 https://www.activitree.com/__meteor__/dynamic-import/fetch                                                                                                    
2019-03-22T18:36:17.380Z + 1 https://www.google-analytics.com/analytics.js                                                                                                                 
2019-03-22T18:36:17.398Z - 0 https://www.google-analytics.com/analytics.js                                                                                                                 
2019-03-22T18:36:17.402Z + 1 https://www.activitree.com/__meteor__/dynamic-import/fetch                                                                                                    
2019-03-22T18:36:17.452Z - 0 https://www.activitree.com/__meteor__/dynamic-import/fetch                                                                                                    
2019-03-22T18:36:17.482Z + 1 https://assets.activitree.com/icons/logo360.png                                                                                                               
2019-03-22T18:36:17.513Z - 0 https://assets.activitree.com/icons/logo360.png                                                                                                               
2019-03-22T18:36:17.638Z + 1 https://www.activitree.com/__meteor__/dynamic-import/fetch                                                                                                    
2019-03-22T18:36:17.703Z - 0 https://www.activitree.com/__meteor__/dynamic-import/fetch                                                                                                    
2019-03-22T18:36:17.705Z level: log text: [object Object] url: /imports/ui/pages/education/EduPage.js line: 1                                                                              
2019-03-22T18:36:17.706Z level: log text: Activitree Education | Schools and Nurseries in UAE url: /imports/ui/pages/education                                                             
/EduPage.js line: 1                                                                                                                                                                        
2019-03-22T18:36:17.723Z level: log text: [object Object] url: /imports/ui/pages/education/EduPage.js line: 1                                                                              
2019-03-22T18:36:17.723Z level: log text: Activitree Education | Canadian Curriculum | Schools and Nurseries in UAE url: /impo                                                             
rts/ui/pages/education/EduPage.js line: 1                                                                                                                                                  
2019-03-22T18:36:17.728Z + 1 https://assets.activitree.com/images/logo-colorx120.png                                                                                                       
2019-03-22T18:36:17.745Z - 0 https://assets.activitree.com/images/logo-colorx120.png                                                                                                       
2019-03-22T18:36:17.786Z level: log text: [object Object] url: /imports/ui/pages/education/EduPage.js line: 1                                                                              
2019-03-22T18:36:17.787Z level: log text: Activitree Education | Canadian Curriculum | Schools and Nurseries in UAE url: /impo                                                             
rts/ui/pages/education/EduPage.js line: 1                                                                                                                                                  
2019-03-22T18:36:17.833Z + 1 https://assets.activitree.com/icons/edu.jpg                                                                                                                   
2019-03-22T18:36:17.834Z + 2 https://assets.activitree.com/icons/gmap.jpg                                                                                                                  
2019-03-22T18:36:17.883Z - 1 https://assets.activitree.com/icons/edu.jpg                                                                                                                   
2019-03-22T18:36:17.885Z - 0 https://assets.activitree.com/icons/gmap.jpg                                                                                                                  
2019-03-22T18:36:18.880Z + 1 https://www.activitree.com/__meteor__/dynamic-import/fetch                                                                                                    
2019-03-22T18:36:18.916Z - 0 https://www.activitree.com/__meteor__/dynamic-import/fetch                                                                                                    
2019-03-22T18:36:22.126Z + 1 https://engine.montiapm.com/errors                                                                                                                            
2019-03-22T18:36:22.195Z - 0 https://engine.montiapm.com/errors                                                                                                                            
2019-03-22T18:36:22.198Z + 1 https://engine.montiapm.com/errors                                                                                                                            
2019-03-22T18:36:22.255Z - 0 https://engine.montiapm.com/errors                                                                                                                            
2019-03-22T18:36:27.064Z + 1 https://engine.montiapm.com/simplentp/sync                                                                                                                    
2019-03-22T18:36:27.096Z - 0 https://engine.montiapm.com/simplentp/sync                                                                                                                    
2019-03-22T18:36:27.100Z + 1 https://engine.montiapm.com/simplentp/sync                                                                                                                    
2019-03-22T18:36:27.141Z - 0 https://engine.montiapm.com/simplentp/sync                                                                                                                    
2019-03-22T18:36:36.377Z page timed out https://www.activitree.com/education/type=all&curr=Canadian                                                                                        
2019-03-22T18:36:36.416Z Restarting Chrome                                                                                                                                                 
2019-03-22T18:36:36.433Z got 200 in 20158ms for https://www.activitree.com/education/type=all&curr=Canadian                                                                                
2019-03-22T18:36:36.434Z Chrome connection closed... restarting Chrome                                                                                                                     
2019-03-22T18:36:36.434Z Starting Chrome                                                                                                                                                   
2019-03-22T18:36:36.953Z Started Chrome: HeadlessChrome/73.0.3683.75  
```
Env vars on the Prerender Node side:

```
BLACKLISTED_DOMAIN: engine.montiapm.com,maps.googleapis.com,www.googletagmanager.com,googletagmanager.com,www.google-analytics.com,google-analytics.com,connect.facebook.net,lc.iadvize.com,fonts.gstatic.com,gstatic.com,i.ytimg.com,www.youtube.com,vimeo.com,www.vimeo.com,baidu.com,f.vimeocdn.com,fresnel.vimeocdn.com,player.vimeo.com,i.vimeocdn.com,youtube.com,player.youtube.com,stats.g.doubleclick.net,static.iadvize.com,api.iadvize.com

BLACKLISTED_DOMAINS: ['engine.montiapm.com', 'maps.googleapis.com']
BLACKLISTED_EXTS: ico,jpg,jpeg,png,ttf,eot,otf,woff,woff2,gif,svg,pdf,css,svg

```
